// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI5-hTgXiHpkN1hQg45JCRbzPvOhq7ZRY',
    appId: '1:1066801771405:web:5efcf6633110968122c3c4',
    messagingSenderId: '1066801771405',
    projectId: 'taskapp-369413',
    authDomain: 'taskapp-369413.firebaseapp.com',
    storageBucket: 'taskapp-369413.appspot.com',
    measurementId: 'G-RG23K7LH6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZm_v7SdOQdiEKw12qeFr17uxF3qOtbXU',
    appId: '1:1066801771405:android:e5244489eef23ddb22c3c4',
    messagingSenderId: '1066801771405',
    projectId: 'taskapp-369413',
    storageBucket: 'taskapp-369413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHsLheShlMRBJcgxMtzl5qCj9nmlYAGWs',
    appId: '1:1066801771405:ios:9e46615187272b1e22c3c4',
    messagingSenderId: '1066801771405',
    projectId: 'taskapp-369413',
    storageBucket: 'taskapp-369413.appspot.com',
    androidClientId: '1066801771405-2b0e2um915lvnkhk4trnbceods07jelf.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHsLheShlMRBJcgxMtzl5qCj9nmlYAGWs',
    appId: '1:1066801771405:ios:2b23e5adfe9807a722c3c4',
    messagingSenderId: '1066801771405',
    projectId: 'taskapp-369413',
    storageBucket: 'taskapp-369413.appspot.com',
    androidClientId: '1066801771405-2b0e2um915lvnkhk4trnbceods07jelf.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp.RunnerTests',
  );
}
